my_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.list_car, name='list_car'),
    # path('list', views.list_car, name='list_car'),
    path('delete_car', views.delete_car, name='delete_car'),
    path('add_car', views.add_car, name='add_car'),
    path('rental_review', views.rental_review, name='rental_review'),
    path('rental_review_stars', views.rental_review_stars, name='rental_review_stars'),
    path('thank_you', views.thank_you, name='thank_you'),
]

my_site/classroom/urls.py
from django.urls import path
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thanks/', views.ThanksView.as_view(), name='thanks1'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('new_teacher/', views.TeacherCreateView.as_view(), name='create_teacher'),
    path('teachers_list/', views.TeacherListView.as_view(), name='list_teacher'),
    path('teachers_detail/<int:pk>', views.TeacherDetailView.as_view(), name='detail_teacher'),
    path('teacher_update/<int:pk>', views.TeacherUpdateView.as_view(), name='update_teacher'),
    path('teacher_delete/<int:pk>', views.TeacherDeleteView.as_view(), name='delete_teacher'),

]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', views.home_view, name='home'),
    # my_app
    path('my_app/', include('my_app.urls')),
    # formdummy
    path('feedback/', include('feedback.urls')),
    # MySiteView
    path('first_app/', include('first_app.urls')),
    # my_templates
    path('my_templates/', include('my_templates.urls')),
    # login
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # office
    path('office/', include('office.urls')),
    # car
    path('cars/', include('cars.urls')),
    #
    path('classroom/', include('classroom.urls')),
]

handler404 = 'my_site.views.my_custom_page_not_found_view'

my_site/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    class Meta:
        verbose_name = "TEACHER"
        verbose_name_plural = "TEACHERS"

    def __str__(self):
        return f'Teacher : {self.first_name}/{self.last_name}/{self.subject}'

my_site/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

my_site/classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,FormView,CreateView,ListView,DetailView,UpdateView,DeleteView
from classroom.forms import ContactForm
from django.urls import reverse,reverse_lazy

from classroom.models import Teacher


# Create your views here.
# https://docs.djangoproject.com/en/4.1/ref/class-based-views/base/#templateview

class HomeView(TemplateView):
    template_name = 'classroom/home.html'


class ThanksView(TemplateView):
    template_name = 'classroom/thanks_page.html'

class ContactFormView(FormView):
    template_name = 'classroom/contact.html'
    form_class = ContactForm

    # success_url = '/classroom/thanks/'
    success_url = reverse_lazy('classroom:thanks1')


    def form_valid(self, form):
        print(form.cleaned_data)
        # {'name': 'Mike', 'message': '55'}
        return super().form_valid(form)

class TeacherCreateView(CreateView):
    model = Teacher
    #model_form.html
    #.save()
    fields = '__all__'
    success_url = '/classroom/thanks/'

class TeacherListView(ListView):
    model = Teacher
    #model_list.html
    queryset = Teacher.objects.order_by('first_name')

    context_object_name = 'teacher_list'
    paginate_by = 25  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class TeacherDetailView(DetailView):
    #model_detail.html
    model = Teacher
    #PK --> {{teacher}}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class TeacherUpdateView(UpdateView):
    #Share model_form.html --- PK
    model = Teacher
    fields = ['first_name','last_name','subject']
    # template_name_suffix = '_update_form'

    success_url = reverse_lazy('classroom:list_teacher')

class TeacherDeleteView(DeleteView):
    #Form --> Confirm Delete Button
    #default template name:
    #model_confirm_delete.html
    model = Teacher


    success_url = reverse_lazy('classroom:list_teacher')

my_site/classroom/templates/classroom/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact form</title>
</head>
<body>
     <h3>Contact form</h3>
     <form method="post">
         {% csrf_token %}
         {{form.as_p}}
         <input type="submit" value="submit">
     </form>
</body>
</html>

my_site/classroom/templates/classroom/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
   <h3>Home page</h3>
    <ul>
        <li>
            <a href="{% url 'classroom:list_teacher' %}">List of teacher </a>
        </li>
        <li>
            <a href="{% url 'classroom:create_teacher' %}">Create new teacher </a>
        </li>
        <li>
            <a href="{% url 'classroom:thanks1' %}">THANKS</a>
        </li>
        <li>
            <a href="{% url 'classroom:contact' %}">Contact page </a>
        </li>
    </ul>
</body>
</html>

my_site/classroom/templates/classroom/teacher_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm delete</title>
</head>
<body>
  <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ teacher }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
   </form>
</body>
</html>

my_site/classroom/templates/classroom/teacher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher detail</title>
</head>
<body>
      {{teacher}}
       <h4> <a href="{% url 'classroom:home' %}">Home</a></h4>
</body>
</html>

my_site/classroom/templates/classroom/teacher_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher</title>
</head>
<body>
     <h3>Teacher form</h3>
     <form method="post">
         {% csrf_token %}
         {{form.as_p}}
         <input type="submit" value="submit">
     </form>
</body>
</html>

my_site/classroom/templates/classroom/teacher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teachers list</title>
</head>
<body>
  <h4>List of techers</h4>
    <ul>
      {% for teacher in teacher_list %}
         <li>
             <a href='/classroom/teachers_detail/{{ teacher.id }}'>{{ teacher.first_name }} - {{ teacher.last_name }} - {{teacher.subject}}</a>
             <ul>
                 <li>
                    <a href='/classroom/teacher_update/{{ teacher.id }}'>Update information</a>
                 </li>
                 <li>
                    <a href='/classroom/teacher_delete/{{ teacher.id }}'>Delete information</a>
                 </li>
             </ul>
         </li>
      {% empty %}
          <li>No teachers yet.</li>
      {% endfor %}
    </ul>
    <h4> <a href="{% url 'classroom:home' %}">Home</a></h4>
</body>
</html>

my_site/classroom/templates/classroom/thanks_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thanks</title>
</head>
<body>
    <h3>Thanks page</h3>
    <ul>
        <li>
            <a href="{% url 'classroom:home' %}">HOME</a>
        </li>
    </ul>
</body>
</html>