my_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.list_car, name='list_car'),
    # path('list', views.list_car, name='list_car'),
    path('delete_car', views.delete_car, name='delete_car'),
    path('add_car', views.add_car, name='add_car'),
    path('rental_review', views.rental_review, name='rental_review'),
    path('rental_review_stars', views.rental_review_stars, name='rental_review_stars'),
    path('thank_you', views.thank_you, name='thank_you'),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', views.home_view, name='home'),
    # my_app
    path('my_app/', include('my_app.urls')),
    # formdummy
    path('feedback/', include('feedback.urls')),
    # MySiteView
    path('first_app/', include('first_app.urls')),
    # my_templates
    path('my_templates/', include('my_templates.urls')),
    # login
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # office
    path('office/', include('office.urls')),
    # car
    path('cars/', include('cars.urls')),
    #
    path('classroom/', include('classroom.urls')),
]

handler404 = 'my_site.views.my_custom_page_not_found_view'

my_site/my_templates/urls.py
from django.urls import path
from . import views

# register the app namespace
# URL NAMES
app_name = 'my_templates'

urlpatterns = [
    path('', views.example_view, name='example1'),
    path('variable', views.variable_view, name='variable'),
    path('loops', views.loops_view, name='loops'),
    path('boolean', views.Bollean_view, name='boolean'),
    path('exBase/', views.exBase_view, name='exBase'),
    path('static/', views.static_view, name='static'),
]

my_site/my_templates/views.py
from django.shortcuts import render


def example_view(request):
    return render(request, "my_templates/example1.html", {})


def variable_view(request):
    some_list = [1, 2, 3]
    some_dict = {'inside_key': 'inside_value'}
    return render(request, "my_templates/variable.html", {'name': 'variable.html',
                                                          'name1': 'variable',
                                                          'some_list': some_list,
                                                          'some_dict': some_dict,
                                                          })


def loops_view(request):
    some_list = [1, 2, 3]
    some_dict = {'inside_key': 'inside_value'}
    return render(request, "my_templates/loops.html", {'name': 'loops.html',
                                                       'name1': 'variable',
                                                       'some_list': some_list,
                                                       'some_dict': some_dict,
                                                       })


def Bollean_view(request):
    some_list = [1, 2, 3]
    some_dict = {'inside_key': 'inside_value'}
    return render(request, "my_templates/boolean.html", {'name': 'bollean.html',
                                                         'name1': 'variable',
                                                         'some_list': some_list,
                                                         'some_dict': some_dict,
                                                         'user_logged_in': True,
                                                         })


def exBase_view(request):
    return render(request, "my_templates/exBase.html", {})


def static_view(request):
    return render(request, "my_templates/static.html", {})

my_site/my_templates/templates/my_templates/boolean.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Boolean</title>
</head>
<body>
<!--  https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#if-->

{% if user_logged_in %}
   <h1>Welcome back you are logged in</h1>
{% else %}
   <h1>You need logg in </h1>
{% endif %}
<hr>
<ul>
{% for num in some_list %}
  {% if num == 2 %}
     <li>Two</li>
  {% else %}
    <li>{{ num }}</li>
  {% endif %}
{% endfor %}
</ul>




</body>
</html>

my_site/my_templates/templates/my_templates/exBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<!--    <title>Title</title>-->
</head>
<body>
{% extends 'base.html' %}

{% block basecontent %}
   <h1>This is inside the block of exBase</h1>
{% endblock %}
</body>
</html>

my_site/my_templates/templates/my_templates/example1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Example1</title>
</head>
<body>
   <h1>example1</h1>
    <h1> <a href="{% url 'my_templates:variable' %}">Variable</a></h1>
</body>
</html>

my_site/my_templates/templates/my_templates/loops.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loops</title>
</head>
<body>
<!--  https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#for-->
 <h1>Loops</h1>
<ul>
  {% for obj_list in some_list %}
    <li>{{obj_list}}</li>
  {% endfor %}
 </ul>
<hr>
<ul>
  {% for key, value in some_dict.items %}
    <li>  {{ key }}: {{ value }}</li>
  {% endfor %}
 </ul>


</body>
</html>

my_site/my_templates/templates/my_templates/static.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--    <title>Title</title>-->
</head>
<body>
{% extends 'base.html' %}
{% load static %}

{% block basecontent %}
<h1>This is inside the block of exBase</h1>
<img src="{% static 'my_templates/1.jpg' %}" alt="image">
{% endblock %}
</body>
</html>

my_site/my_templates/templates/my_templates/variable.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Variable HTML</title>
</head>
<body>
<!--  https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#filter-->
<h1>{{name | upper }}</h1>
<h1>{{name1 | length}}</h1>
<h2>{{some_list.0}}</h2>
<h2>{{some_dict.inside_key}}</h2>
<h2>{# this is comment #}</h2>
<h1><a href="{% url 'my_templates:example1' %}">example</a></h1>
</body>
</html>