my_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.list_car, name='list_car'),
    # path('list', views.list_car, name='list_car'),
    path('delete_car', views.delete_car, name='delete_car'),
    path('add_car', views.add_car, name='add_car'),
    path('rental_review', views.rental_review, name='rental_review'),
    path('rental_review_stars', views.rental_review_stars, name='rental_review_stars'),
    path('thank_you', views.thank_you, name='thank_you'),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', views.home_view, name='home'),
    # my_app
    path('my_app/', include('my_app.urls')),
    # formdummy
    path('feedback/', include('feedback.urls')),
    # MySiteView
    path('first_app/', include('first_app.urls')),
    # my_templates
    path('my_templates/', include('my_templates.urls')),
    # login
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # office
    path('office/', include('office.urls')),
    # car
    path('cars/', include('cars.urls')),
    #
    path('classroom/', include('classroom.urls')),
]

handler404 = 'my_site.views.my_custom_page_not_found_view'

my_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--    <title>Title</title>-->
</head>
<body>

<h1>This is above the block in Base.html</h1>
{% block basecontent %}

{% endblock basecontent %}
<h1>This is below the block in Base.html</h1>
</body>
</html>

my_site/templates/base_car.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base car</title>
    <!--https://getbootstrap.com/docs/5.1/getting-started/introduction/-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'cars/custom.css'  %}">
</head>
<body>
<!--  NAVBAR-->
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <a class="nav-link" href="{% url 'cars:list_car' %}">LIST</a>
                <a class="nav-link" href="{% url 'cars:add_car' %}">ADD</a>
                <a class="nav-link" href="{% url 'cars:delete_car' %}">DELETE</a>
                <a class="nav-link" href="{% url 'cars:rental_review' %}">Feedback</a>
                <a class="nav-link" href="{% url 'cars:rental_review_stars' %}">Feedback stars</a>
            </ul>
        </div>
    </div>
</nav>
{% block content %}

{% endblock content %}
</body>
</html>

my_site/templates/error_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error view</title>
</head>
<body>
<h1>Error view</h1>
</body>
</html>